<?php

namespace App\Livewire\Admin\Department;

use Livewire\Component;
use App\Models\Department;

class DepartmentForm extends Component
{
    public ?Department $department = null;
    public $ma_phong_ban = '';
    public $ten_phong_ban = '';
    public $ma_mau = '#3B82F6';
    public $trang_thai = 'hoat_dong';
    
    protected $rules = [
        'ten_phong_ban' => 'required|string|max:100',
        'ma_mau' => 'required|regex:/^#[0-9A-Fa-f]{6}$/',
        'trang_thai' => 'required|in:hoat_dong,tam_ngung',
    ];
    
    protected $messages = [
        'ten_phong_ban.required' => 'Tên phòng ban không được để trống.',
        'ten_phong_ban.max' => 'Tên phòng ban không được vượt quá 100 ký tự.',
        'ma_mau.required' => 'Mã màu không được để trống.',
        'ma_mau.regex' => 'Mã màu phải có định dạng hex (ví dụ: #FF5733).',
    ];
    
    public function mount($id = null)
    {
        if ($id) {
            $this->department = Department::findOrFail($id);
            $this->ma_phong_ban = $this->department->ma_phong_ban;
            $this->ten_phong_ban = $this->department->ten_phong_ban;
            $this->ma_mau = $this->department->ma_mau;
            $this->trang_thai = $this->department->trang_thai;
        }
    }
    
    public function save()
    {
        $this->validate();
        
        $data = [
            'ten_phong_ban' => $this->ten_phong_ban,
            'ma_mau' => $this->ma_mau,
            'trang_thai' => $this->trang_thai,
        ];
        
        if ($this->department) {
            // Update existing department
            $this->department->update($data);
            session()->flash('success', 'Cập nhật phòng ban thành công!');
        } else {
            // Create new department (ma_phong_ban will be auto-generated by HasUniqueCode trait)
            Department::create($data);
            session()->flash('success', 'Thêm phòng ban thành công!');
        }
        
        return redirect()->route('admin.departments.index');
    }
    
    public function render()
    {
        return view('livewire.admin.department.department-form')
            ->layout('components.layouts.admin', [
                'pageTitle' => $this->department ? 'Sửa Phòng Ban' : 'Thêm Phòng Ban',
                'breadcrumbs' => [
                    ['label' => 'Phòng ban', 'url' => route('admin.departments.index')],
                    ['label' => $this->department ? 'Sửa' : 'Thêm mới'],
                ]
            ]);
    }
}
