<?php

namespace App\Livewire\Admin\Supplier;

use App\Models\Supplier;
use Livewire\Component;
use Livewire\Attributes\Layout;

#[Layout('components.layouts.app')]
class SupplierForm extends Component
{
    public ?Supplier $supplier = null;
    public $ma_ncc = '';
    public $ten_ncc = '';
    public $nguoi_dai_dien = '';
    public $so_dien_thoai = '';
    public $so_dien_thoai_zalo = '';
    public $dia_chi = '';
    public $email = '';
    public $san_pham_cung_cap = '';
    public $noi_dung_thoa_thuan = '';
    public $ghi_chu = '';

    public function mount($id = null)
    {
        if ($id) {
            $this->supplier = Supplier::findOrFail($id);
            $this->ma_ncc = $this->supplier->ma_ncc;
            $this->ten_ncc = $this->supplier->ten_ncc;
            $this->nguoi_dai_dien = $this->supplier->nguoi_dai_dien;
            $this->so_dien_thoai = $this->supplier->so_dien_thoai;
            $this->so_dien_thoai_zalo = $this->supplier->so_dien_thoai_zalo;
            $this->dia_chi = $this->supplier->dia_chi;
            $this->email = $this->supplier->email;
            $this->san_pham_cung_cap = $this->supplier->san_pham_cung_cap;
            $this->noi_dung_thoa_thuan = $this->supplier->noi_dung_thoa_thuan;
            $this->ghi_chu = $this->supplier->ghi_chu;
        } else {
            // Auto-generate code for new supplier
            $this->ma_ncc = (new Supplier)->generateUniqueCode();
        }
    }

    public function save()
    {
        $this->validate([
            'ten_ncc' => 'required|min:2',
            'email' => 'nullable|email',
        ]);

        $data = [
            'ten_ncc' => $this->ten_ncc,
            'nguoi_dai_dien' => $this->nguoi_dai_dien,
            'so_dien_thoai' => $this->so_dien_thoai,
            'so_dien_thoai_zalo' => $this->so_dien_thoai_zalo,
            'dia_chi' => $this->dia_chi,
            'email' => $this->email,
            'san_pham_cung_cap' => $this->san_pham_cung_cap,
            'noi_dung_thoa_thuan' => $this->noi_dung_thoa_thuan,
            'ghi_chu' => $this->ghi_chu,
        ];

        if ($this->supplier) {
            // Update (code không đổi)
            $this->supplier->update($data);
            session()->flash('message', 'Cập nhật nhà cung cấp thành công.');
        } else {
            // Create (code auto-generated by trait)
            Supplier::create($data);
            session()->flash('message', 'Thêm mới nhà cung cấp thành công.');
        }

        return redirect()->route('admin.suppliers.index');
    }

    public function render()
    {
        return view('livewire.admin.supplier.supplier-form');
    }
}
