<?php

namespace App\Livewire\Admin\User;

use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Livewire\Component;
use Livewire\Attributes\Layout;
use Livewire\WithFileUploads;

#[Layout('components.layouts.app')]
class UserForm extends Component
{
    use WithFileUploads;
    public ?User $user = null;
    
    // Basic info
    public $ma_nhan_vien = '';
    public $ho_ten = '';
    public $email = '';
    public $password = '';
    public $so_dien_thoai = '';
    public $facebook = '';
    public $dia_chi = '';
    
    // Contract
    public $loai_hop_dong = 'thu_viec';
    public $ngay_ky_hop_dong = '';
    public $ngay_het_han_hop_dong = '';
    public $ngay_thu_viec = '';
    public $ngay_chinh_thuc = '';
    public $ghi_chu_hop_dong = '';
    
    // File upload
    public $file_hop_dong = null;
    public $existing_file = null;
    
    // Salary
    public $luong_thu_viec = 0;
    public $luong_chinh_thuc = 0;
    public $loai_luong = 'theo_ngay';
    
    // System
    public $vai_tro = 'nhan_vien';
    public $trang_thai = 'hoat_dong';

    public function mount($id = null)
    {
        if ($id) {
            $this->user = User::findOrFail($id);
            $this->ma_nhan_vien = $this->user->ma_nhan_vien;
            $this->ho_ten = $this->user->ho_ten;
            $this->email = $this->user->email;
            $this->so_dien_thoai = $this->user->so_dien_thoai;
            $this->facebook = $this->user->facebook;
            $this->dia_chi = $this->user->dia_chi;
            $this->loai_hop_dong = $this->user->loai_hop_dong ?? 'thu_viec';
            $this->ngay_ky_hop_dong = $this->user->ngay_ky_hop_dong?->format('Y-m-d');
            $this->ngay_het_han_hop_dong = $this->user->ngay_het_han_hop_dong?->format('Y-m-d');
            $this->ngay_thu_viec = $this->user->ngay_thu_viec?->format('Y-m-d');
            $this->ngay_chinh_thuc = $this->user->ngay_chinh_thuc?->format('Y-m-d');
            $this->ghi_chu_hop_dong = $this->user->ghi_chu_hop_dong;
            $this->existing_file = $this->user->file_hop_dong;
            $this->luong_thu_viec = $this->user->luong_thu_viec ?? 0;
            $this->luong_chinh_thuc = $this->user->luong_chinh_thuc ?? 0;
            $this->loai_luong = $this->user->loai_luong ?? 'theo_ngay';
            $this->vai_tro = $this->user->vai_tro;
            $this->trang_thai = $this->user->trang_thai;
        } else {
            // Auto-generate code preview for new user
            $this->ma_nhan_vien = (new User)->generateUniqueCode();
        }
    }

    public function save()
    {
        $this->validate([
            'ho_ten' => 'required|min:3',
            'email' => 'required|email|unique:nguoi_dung,email,' . ($this->user->id ?? 'NULL'),
            'password' => $this->user ? 'nullable|min:6' : 'required|min:6',
            'vai_tro' => 'required|in:admin,nhan_vien',
            'trang_thai' => 'required|in:hoat_dong,khoa',
            'loai_hop_dong' => 'nullable|in:thu_viec,chinh_thuc,hop_tac',
            'file_hop_dong' => 'nullable|file|mimes:pdf,jpg,jpeg,png|max:5120', // 5MB max
        ]);

        $data = [
            'ho_ten' => $this->ho_ten,
            'email' => $this->email,
            'so_dien_thoai' => $this->so_dien_thoai,
            'facebook' => $this->facebook,
            'dia_chi' => $this->dia_chi,
            'loai_hop_dong' => $this->loai_hop_dong,
            'ngay_ky_hop_dong' => $this->ngay_ky_hop_dong,
            'ngay_het_han_hop_dong' => $this->ngay_het_han_hop_dong,
            'ngay_thu_viec' => $this->ngay_thu_viec,
            'ngay_chinh_thuc' => $this->ngay_chinh_thuc,
            'ghi_chu_hop_dong' => $this->ghi_chu_hop_dong,
            'luong_thu_viec' => $this->luong_thu_viec,
            'luong_chinh_thuc' => $this->luong_chinh_thuc,
            'loai_luong' => $this->loai_luong,
            'vai_tro' => $this->vai_tro,
            'trang_thai' => $this->trang_thai,
        ];

        if ($this->password) {
            $data['mat_khau'] = Hash::make($this->password);
        }
        
        // Handle file upload
        if ($this->file_hop_dong) {
            $maNhanVien = $this->user ? $this->user->ma_nhan_vien : $this->ma_nhan_vien;
            $filename = 'hop-dong-' . time() . '.' . $this->file_hop_dong->extension();
            $path = $this->file_hop_dong->storeAs(
                'contracts/' . $maNhanVien,
                $filename,
                'public'
            );
            $data['file_hop_dong'] = $path;
        }

        if ($this->user) {
            // Update existing (code không đổi)
            $this->user->update($data);
            session()->flash('message', 'Cập nhật nhân viên thành công.');
        } else {
            // Create new (code auto-generated by trait)
            User::create($data);
            session()->flash('message', 'Thêm mới nhân viên thành công.');
        }

        return redirect()->route('admin.users.index');
    }

    public function render()
    {
        return view('livewire.admin.user.user-form');
    }
}
