<?php

namespace App\Livewire\Admin\Product;

use App\Models\Product;
use App\Models\ProductCategory;
use Livewire\Component;
use Livewire\Attributes\Layout;

#[Layout('components.layouts.app')]
class ProductForm extends Component
{
    public ?Product $product = null;
    public $ma_san_pham = '';
    public $ten_san_pham = '';
    public $danh_muc_id = '';
    public $mo_ta = '';
    public $gia_ban = 0;
    public $don_vi_tinh = 'cái';
    public $don_vi_phan_phoi = '';
    public $so_luong_quy_doi = 1;
    public $trang_thai = 'con_hang';

    public function mount($id = null)
    {
        if ($id) {
            $this->product = Product::findOrFail($id);
            $this->ma_san_pham = $this->product->ma_san_pham;
            $this->ten_san_pham = $this->product->ten_san_pham;
            $this->danh_muc_id = $this->product->danh_muc_id;
            $this->mo_ta = $this->product->mo_ta;
            $this->gia_ban = $this->product->gia_ban;
            $this->don_vi_tinh = $this->product->don_vi_tinh;
            $this->don_vi_phan_phoi = $this->product->don_vi_phan_phoi;
            $this->so_luong_quy_doi = $this->product->so_luong_quy_doi ?? 1;
            $this->trang_thai = $this->product->trang_thai;
        } else {
            // Auto-generate code for new product
            $this->ma_san_pham = (new Product)->generateUniqueCode();
        }
    }

    public function save()
    {
        $this->validate([
            'ten_san_pham' => 'required|min:2',
            'gia_ban' => 'required|numeric|min:0',
            'don_vi_tinh' => 'required',
            'so_luong_quy_doi' => 'nullable|integer|min:1',
            'trang_thai' => 'required|in:con_hang,het_hang,ngung_ban',
        ]);

        $data = [
            'ten_san_pham' => $this->ten_san_pham,
            'danh_muc_id' => $this->danh_muc_id ?: null,
            'mo_ta' => $this->mo_ta,
            'gia_ban' => $this->gia_ban,
            'don_vi_tinh' => $this->don_vi_tinh,
            'don_vi_phan_phoi' => $this->don_vi_phan_phoi ?: null,
            'so_luong_quy_doi' => $this->so_luong_quy_doi ?: 1,
            'trang_thai' => $this->trang_thai,
        ];

        if ($this->product) {
            // Update (code không đổi)
            $this->product->update($data);
            session()->flash('message', 'Cập nhật sản phẩm thành công.');
        } else {
            // Create (code auto-generated by trait)
            Product::create($data);
            session()->flash('message', 'Thêm mới sản phẩm thành công.');
        }

        return redirect()->route('admin.products.index');
    }

    public function messages()
    {
        return [
            'ten_san_pham.required' => 'Tên sản phẩm là bắt buộc.',
            'ten_san_pham.min' => 'Tên sản phẩm phải có ít nhất 2 ký tự.',
            'gia_ban.required' => 'Giá bán là bắt buộc.',
            'gia_ban.min' => 'Giá bán không được nhỏ hơn 0.',
            'don_vi_tinh.required' => 'Đơn vị tính là bắt buộc.',
            'so_luong_quy_doi.min' => 'Số lượng quy đổi phải lớn hơn 0.',
        ];
    }

    public function render()
    {
        $categories = ProductCategory::orderBy('thu_tu')->get();
        return view('livewire.admin.product.product-form', [
            'categories' => $categories,
        ]);
    }
}
